### ISSUE TITLE
Consumption plan support still planned?

### ISSUE THREAD

**Issue by IGx89** [microsoft/durabletask-mssql#115]
Hello! The quick start documentation says the following:

> At the time of writing, the Durable SQL provider is in its early stages and does not yet work with the Azure Functions Consumption plan. It does work with the Azure Functions Elastic Premium plan but you must enable [Runtime Scale Monitoring](https://docs.microsoft.com/azure/azure-functions/functions-networking-options#premium-plan-with-virtual-network-triggers) to get automatic scaling. App Service plans are also supported. Consumption plan support and Scale Controller support for Elastic Premium is coming in a later release.

That seems to say that consumption plan support is planned. Is that still the case?

**Comment by cgillum** [comment]
Yes, Consumption plan support has been completed and we're just waiting for it to roll out to all Azure Functions production regions. We'll send a GA announcement and update the documentation (including [here](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-storage-providers#comparing-storage-providers)) once it's ready to be used.

**Comment by IGx89** [comment]
That's great news, thank you!

**Comment by IGx89** [comment]
hi @cgillum! Any updates on the consumption plan support rollout? Docs still say it's not supported, but a rollout taking multiple months seems odd as well. If there's an issue I could watch instead of bugging you, just LMK :). Thanks!

**Comment by cgillum** [comment]
I completely agree that a deployment taking multiple months seems odd - yet unfortunately that's the current state of things. Some changes are being made so that future changes won't take this long (they will use a different deployment mechanism designed to avoid these kinds of delays). We're close, though - somewhere in the 90%+ range of completion.
