### ISSUE TITLE
WaitForOrchestrationAsync does not work

### ISSUE THREAD

**Issue by mol-pensiondk** [microsoft/durabletask-mssql#121]
The call
```
var os = await _taskHubClient.WaitForOrchestrationAsync(orchestrationInstance, TimeSpan.MaxValue);
```
never finishes (that is, the task never finishes) with the MSSQL backend. It works fine with the Azure Storage backend, returning the orchestration status once the given orchestration instance has reached a final state.

**Comment by cgillum** [comment]
@mol-pensiondk can you provide a simple reproducer for this? Nearly all of our orchestration integration tests indirectly depend on this API ([reference](https://github.com/microsoft/durabletask-mssql/blob/56fa416be8740c60840620b9a5cf8a685dc18343/test/DurableTask.SqlServer.Tests/Utils/TestInstance.cs#L78)).

**Comment by mol-pensiondk** [comment]
While simplifying my code to provide a reproducer I found that the problem is not that the task never finishes but rather that the call to `WaitForOrchestrationAsync` itself throws an exception (this was hidden form me before because it ran in a background task that was not awaited). The problem is that [here](https://github.com/microsoft/durabletask-mssql/blob/531422c6260bed46495dd91bb4741f1f675a6dc9/src/DurableTask.SqlServer/SqlOrchestrationService.cs#L535) the constructor of `CancellationToken` throws because `TimeSpan.MaxValue`is out of range. Replacing `TimeSpan.MaxValue` in my call with `TimeSpan.FromMilliseconds(Int32.MaxValue)` avoids this and then the task is started and finishes on orchestration completion as expected.

The Azure Storage backend accepts `TimeSpan.MaxValue`, so cannot be relying on that `CancellationToken` mechanism. It would be nice if the MSSQL backend would not have this limitation on the `TimeSpan` values allowed in `WaitForOrchestrationAsync`, as `TimeSpan.MaxValue` is a natural way to indicate that no timeout is wanted.
