### ISSUE TITLE
External client ignores task hub name configuration

### ISSUE THREAD

**Issue by bhugot** [microsoft/durabletask-mssql#127]
Hello, 
When using an external client with sql provider. the specified task hub is ignored. The only way to have the specified task hub used is actually to use this
```CS
services.Configure<DurableTaskOptions>(options =>
        {
            options .HubName = "CustomTaskHub";
        });
```
But it's only one taskhub that could be use this way. And we need to be able to ask for many task hub on same sql schema.
What we do is 
```CS
private async Task<IReadOnlyCollection<DurableOrchestrationStatus>> SearchPerTaskHubAsync(string taskHub,
        OrchestrationStatusQueryCondition condition, CancellationToken cancellationToken)
    {
        var client = _durableClientFactory.CreateClient(new DurableClientOptions
        {
            TaskHub = taskHub // <-- this is not used
        });
        var result = new List<DurableOrchestrationStatus>();
        while (true)
        {
            var page = await client.ListInstancesAsync(condition, cancellationToken);
            result.AddRange(page.DurableOrchestrationState);
            if(string.IsNullOrEmpty(page.ContinuationToken))
                return result;
            condition.ContinuationToken = page.ContinuationToken;
        }
    }
```

**Comment by bhugot** [comment]
I should have we activated ```EXECUTE dt.SetGlobalSetting @Name='TaskHubMode', @Value=0```

**Comment by bhugot** [comment]
Ok I think that I have found the root cause of it
https://github.com/microsoft/durabletask-mssql/blob/531422c6260bed46495dd91bb4741f1f675a6dc9/src/DurableTask.SqlServer.AzureFunctions/SqlDurabilityProviderFactory.cs#L90 it's creating another SqlOrchestrationService instead of using the one created correctly one line before so it should instead do that 
```CS
SqlOrchestrationService orchestrationService = new SqlOrchestrationService(clientOptions.GetOrchestrationServiceSettings(
                    this.extensionOptions,
                    this.connectionInfoResolver));
                clientProvider = new SqlDurabilityProvider(
                    orchestrationService,
                    clientOptions);
```

**Comment by cgillum** [comment]
@bhugot the thing that's blocking the release is that I need to put together [a suite of schema upgrade/compatibility tests](https://github.com/microsoft/durabletask-mssql/issues/124) now that we've reached the stable release versions. This will take some time and we don't have a date for it yet.  I can get you a preview package if you're okay without it containing any database upgrade compatibility validation.

**Comment by bhugot** [comment]
Would be great for the preview.

**Comment by cgillum** [comment]
OK. You can find the preview nuget packages uploaded here:
* [Microsoft.DurableTask.SqlServer](https://www.myget.org/feed/azure-appservice/package/nuget/Microsoft.DurableTask.SqlServer)
* [Microsoft.DurableTask.SqlServer.AzureFunctions](https://www.myget.org/feed/azure-appservice/package/nuget/Microsoft.DurableTask.SqlServer.AzureFunctions)

**Comment by bhugot** [comment]
Thanks alot
