### ISSUE TITLE
Orchestration with a lot of activities call with Task.WhenAll take sometimes alot of time to be mark as completed

### ISSUE THREAD

**Issue by bhugot** [microsoft/durabletask-mssql#131]
Hello, 
Time to time we have some orchestration in the following state:
Instance is Running
Task is empty
All Events related to the instance are completed and they are removed slowly from events according to the 
taskEventBatchSize and taskEventLockTimeout. 
Any idea how to fix this?

**Comment by bhugot** [comment]
Maybe it's related . Azure recommand to add 
`CREATE NONCLUSTERED INDEX [nci_wi_NewEvents_0C4B0C7A9B472311807DF4F70A041684] ON [dt].[NewEvents] ([TaskHub], [VisibleTime]) WITH (ONLINE = ON)`

**Comment by cgillum** [comment]
Can you provide more details about how to reproduce this problem? How many activities is your orchestration running in parallel?

**Comment by bhugot** [comment]
Hello can be 50K or more

**Comment by bhugot** [comment]
I think this could also be fixed by #134
