### ISSUE TITLE
Relpay failed activities

### ISSUE THREAD

**Issue by bbenameur** [microsoft/durabletask-mssql#157]
Hello,

Is there a features to replay only failed activities on the orchestrations?

Thanks

**Comment by cgillum** [comment]
When you call an activity, you can provide a retry policy, if that's what you're asking. With the retry policy, you can have failed activities retry based on some configuration, including backoff intervals, etc.

**Comment by bbenameur** [comment]
No it's not about a retry policy, i mean for example i have an orchestration with id xxxxxx,
that contain the 2 first activties was successed and 3 other failed,
when Replay all orchestration with ID, orchestration should start from failed acitivities, 
it's like a restart orchestration but it should start from failed activities.

**Comment by bhugot** [comment]
It s rewind

**Comment by cgillum** [comment]
Indeed, this sounds like a description of the rewind API.

* If you're taking a direct dependency on Microsoft.DurableTask.SqlServer, you can use the [SqlOrchestrationService.RewindOrchestrationInstanceAsync()](https://github.com/microsoft/durabletask-mssql/blob/a806eea817cc4bf95ba5426635d2c8339528bb9d/src/DurableTask.SqlServer/SqlOrchestrationService.cs#L849) API for this.
* If you're using Azure Durable Functions, you can use the [rewind REST API](https://learn.microsoft.com/azure/azure-functions/durable/durable-functions-http-api#rewind-instance-preview) or the language-specific SDK API to do the same.

**Comment by bbenameur** [comment]
This is exactly what i want , thanks you !
