### ISSUE TITLE
Dashboard/admin panel for checking the statuses of orchestrations/activities in the DB

### ISSUE THREAD

**Issue by Nabakamal** [microsoft/durabletask-mssql#158]
I don't know if one exists, or anyone has some idea/s around it, but, how can I find the "health" (and maybe other stats) of my orchestrations/activities? 
In essence, this would be a matrix of the data stored in the SQL DB (from tables like Payloads, History, etc.).
Additionally, if this board gives us the capability to "restart" an existing orchestration, find out what went wrong with a particular orchestration, etc. then that'd be great(admin panel feature). 

Obviously, this should not be "too" difficult to build but I don't want to reinvent the wheel and start doing something that might already be there. 

Presently looking at: https://github.com/microsoft/DurableFunctionsMonitor/wiki

As for the DB-hosting bit, we are using an on-premise SQL Server at present. The idea to use DTFx is so that we can port this piece over without too much hassle when we move our code to the cloud.  

If this question doesn't belong here, I can move this out to the larger group for durable tasks. Please advise. 

Thank you.

**Comment by Nabakamal** [comment]
I may be answering my same question but https://github.com/microsoft/DurableFunctionsMonitor/tree/main/custom-backends/mssql#durable-functions-monitor-for-mssql-storage-provider might help me.

**Comment by bhugot** [comment]
Yes this is it

**Comment by bachuv** [comment]
@Nabakamal, the link you added in your comment should help. I'm going to close this issue, but feel free to reopen it or create another issue if you have questions. Thanks!
