### ISSUE TITLE
Exception is not propagated to parent orchestration as expected

### ISSUE THREAD

**Issue by moldovangeorge** [microsoft/durabletask-mssql#161]
Irrespective of the [ErrorPropagationMode](https://github.com/Azure/durabletask/blob/c2c51c2ab9411eb0e440b4c508985e3d53c2e14e/src/DurableTask.Core/ErrorPropagationMode.cs ) value that is set on the worker when running based on the SqlServerProvider, the Exception is not propagated up the stack as expected. 
My expectation was that the Exception that is caught in the parent orchestration would contain the exception that was thrown in the Activity either in the innerException field, or in the FailureDetails field. 
![image](https://user-images.githubusercontent.com/73134867/228214917-702dc566-c477-49d4-bef6-b95bbb7ec50e.png)
I ran a demo app using both UseFailureDetails and UseFailureDetails setup and in both cases the exception was not propagated correctly, and it only contained limited information in the message of the exception ( either the message of the inner exception, or the type of the inner exception, depending if the inner exception had a message or not). 

Also, when using the UseFailureDetails setup, I expected to receive an OrchestrationException in parent orchestration but a TaskFailedException was raised instead.

**Comment by wros** [comment]
I have this same problem using the function, in isolated mode. The Exception is not propagated to the orchestration, and I cannot use the custom retry in the activity.

I'm using the Azure Version.

When I use the SQL Provider

![image](https://github.com/microsoft/durabletask-mssql/assets/26489708/0d4f48e0-98fc-4bc9-8095-9bf43104b830)

Here when I don't use the SQL Provider:

![image](https://github.com/microsoft/durabletask-mssql/assets/26489708/7798d59f-b189-4341-bef8-ef017ab0c571)

Obs: I'm using the VS 2022 default template for Azure Functions.

**Comment by cgillum** [comment]
Thanks @wros for the additional context. This helps narrow things down. I haven't had a chance to look at this yet but hoping to get to it soon'ish.

**Comment by cgillum** [comment]
I spent some time debugging this and I think the problem is that the database schema needs to be updated to support correctly persisting detailed exception information. From what I can tell, we're only saving the exception message, which isn't something we can correctly deserialize back into code. This is definitely a missing feature.
