### ISSUE TITLE
Fully scripted deployment not easy with the dt_rutime role added at runtime

### ISSUE THREAD

**Issue by andsj073** [microsoft/durabletask-mssql#168]
Hello

As the schema, specifically the role `dt_runtime`, is created automatically at runtime with the execution of a Durable Function<SQL Provider>, it is challenging to fully script the deployment of a solution to for example Azure (but same goes for any environment in general).

As I understand it, as solution pipeline would need to be something like the following:
1. Run a script that deploys all resources (e.g. for Azure a SQL Database and Function App, DurableDB database and Function etc)
2. Execute a shell script that runs the SQL commands that create the Durable Function<SQL Provider> authentication login and user of role `db_owner` role (as `dt_runtime` does not yet exist)
3. Somehow script an initial execution of the Durable Function deployed to get the DT schema created (for example a shell script that invokes a Function trigger)
4. Execute a shell script that runs the SQL commands that modify the user from step 2 adding it to the `dt_runtime` role and dropping from `db_owner`

Challenges with steps 2-4 : 
- not straight-forward to automate (as for example with ARM templates, Bicep etc) 
- triggering a function could be challenging in locked-down a production environment 
- adds comparatively long lead time to pipeline execution
- grants unnecessary high privileges to a DB user albeit for a short time

Is there a workaround that you can propose? 
Could for example the pipeline add a placeholder role called `dt_runtime` to the DurableDB database at step 2, which would later, during actual durable function execution (not necessarily scripted), be updated with the correct definition by the SQL Provider?

Or will this require some kind of feature enhancement?

Thank you for you great work!

**Comment by andsj073** [comment]
Hi @cgillum
Yes, something like that.

We are onboarding customers to a multi-tenant solution and for each such we run a bicep script that deploys a function app (with durable functions using SQL as taskhub provider) and a database on a common azure sql database server. The script assigns the MI of the app the db_owner (as dt_runtime does not exist at this point in time) role of DurableDB for DT schema creation (and dbmanager of master).

After the script we need to manually trigger the function to run, and after that go to SSMS to change the role assignment from db_owner to dt_runtime.

This is not scalable and have some (small) security concerns.

So yes, way to to fully script schema creation, be it with T-SQL statements in a file

Thank you!

**Comment by vigouredelaruse** [comment]
@andsj073 are you referring to the scripts here? https://github.com/microsoft/durabletask-mssql/blob/main/src/DurableTask.SqlServer/Scripts/schema-1.0.0.sql
