### ISSUE TITLE
Configurable minimum for backoff retry for polling interval

### ISSUE THREAD

**Issue by dmetzgar** [microsoft/durabletask-mssql#172]
We have a lot of pods all polling for new tasks and instances in our database. Even with regular cleanup we have over 1 million instances. The queries to poll for instances (new or lease expired) and new tasks take 27% and 18% of available DTUs respectively (database is a P6: 1000 DTU). Given the stats, we're seeing an average of 12 polls for new instances per second. New task polling is similar. For our use cases, this is unnecessary. The minimum interval of 50ms on the backoff retry is also used as the delta backoff increment. So increasing the max interval doesn't help. We need to be able to configure the min interval as well.

**Comment by cgillum** [comment]
Thanks @dmetzgar for this info. 12 polls/second is definitely overkill. In the short term, I think adding some new properties to `SqlOrchestrationServiceSettings` would be a good way to make the polling configurable. Longer term, we should probably auto-adjust these values as we scale out (something I've been thinking about as part of #58) to ensure we don't poll more than N times per second total.
