### ISSUE TITLE
chatty azure insights traces

### ISSUE THREAD

**Issue by vigouredelaruse** [microsoft/durabletask-mssql#173]
the durable functions sql provider generates many traces when the orchestration is instrumented with azure application insights as per
![image](https://github.com/microsoft/durabletask-mssql/assets/31052867/b1b06b5f-9564-4b25-b2bd-4da7140483cd)

is there a way to adjust the log frequency with configuration of the sql provider?

**Comment by cgillum** [comment]
This is not expected. Are you running in Azure Functions (cloud) or locally, using the Azure Core Tools? Also, what is the logging configuration that you have in host.json?

**Comment by vigouredelaruse** [comment]
let me get back to you

**Comment by vigouredelaruse** [comment]
sorry for the long validation pause - no longer seeing this- 'false alarm'
