### ISSUE TITLE
Azure Managed Identity support

### ISSUE THREAD

**Issue by cgillum** [microsoft/durabletask-mssql#18]
Currently we support connecting to a SQL database using Windows Integrated Auth or via username/password. Support for Azure Managed Identity would be helpful for users that are running in Azure (w/out Windows Integrated Auth support) and don't want to put database credentials in their application configuration.

Useful resource for instructions on how this works generally: https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/tutorial-windows-vm-access-sql

Useful code that can be borrowed for obtaining an access token: https://github.com/Azure/azure-functions-durable-extension/blob/47247f9ab322efdf9cd9216582bc5a7dce9bb37f/src/WebJobs.Extensions.DurableTask/ManagedIdentityTokenSource.cs#L55-L79

**Comment by usemam** [comment]
@cgillum
Hi!
Could you please take a look at [this commit](https://github.com/usemam/durabletask-mssql/commit/732aec4a8600056aae15785eac0647971e09dbad)?
If it's not really bad - I'll create a PR.
Thanks!

**Comment by cgillum** [comment]
@usemam this looks great! There are many a few tiny tweaks I would suggest, but if you're willing to create a PR, I can provide the more detailed feedback and we can get it merged!
