### ISSUE TITLE
Incorrect Calculation of GetRecommendedScale due to UTC/Local Time formats in tables

### ISSUE THREAD

**Issue by tshaiman** [microsoft/durabletask-mssql#180]
Hi,
Our team just onboarded to  Durable Task on SQL and is now on phase of testing the framework.
when we tried to scale our orchestration , we found that the GetRecommendedScale function always return "0" .
( or "1" for a very short time - few seconds).

we have a hunch on what is the root cause of it : 

**1**
the "newEvent" table has a 2 time columns - one is of UTC and the other is on Local time ( in our case UTC+2).
hence when we call the "getScaleRecommendation" we get "0" since the code uses the following SQL Query : 

```
BEGIN
    DECLARE @taskHub varchar(50) = dt.CurrentTaskHub()
    DECLARE @now datetime2 = SYSUTCDATETIME() --> **This is UTC**

    DECLARE @liveInstances int = 0
    DECLARE @liveTasks int = 0

    SELECT
        @liveInstances = COUNT(DISTINCT E.[InstanceID]),
        @liveTasks = COUNT(T.[InstanceID])
    FROM Instances I WITH (NOLOCK)
        LEFT OUTER JOIN NewEvents E WITH (NOLOCK) ON E.[TaskHub] = @taskHub AND E.[InstanceID] = I.[InstanceID]
        LEFT OUTER JOIN NewTasks T WITH (NOLOCK) ON T.[TaskHub] = @taskHub AND T.[InstanceID] = I.[InstanceID]
    WHERE
        I.[TaskHub] = @taskHub
        AND I.[RuntimeStatus] IN ('Pending', 'Running')
        AND (E.[VisibleTime] IS NULL OR E.[VisibleTime] < @now)   **E.VisibileTime is LocalTime**

    IF @MaxOrchestrationsPerWorker < 1 SET @MaxOrchestrationsPerWorker = 1
    IF @MaxActivitiesPerWorker < 1 SET @MaxActivitiesPerWorker = 1

    DECLARE @recommendedWorkersForOrchestrations int = CEILING(@liveInstances / @MaxOrchestrationsPerWorker)
    DECLARE @recommendedWorkersForActivities int = CEILING(@liveTasks / @MaxActivitiesPerWorker)

    RETURN @recommendedWorkersForOrchestrations + @recommendedWorkersForActivities
END
```

The result is that on the same row on that table you get two mixed datetime formats : 
![image](https://github.com/microsoft/durabletask-mssql/assets/512709/ae6d2bd3-9518-4b02-aea3-f0ed76129af0)

while the timestamp is in UTC the visibleTime is in local time. 
Both columns got update in real-time in less then 1 minute difference.

**2**

the NewTasks table is always empty

**3**
please check if the   COUNT(DISTINCT E.[InstanceID]), needs to be distinct.

thanks
Tomer

@cgillum

**Comment by davidmrdavid** [comment]
Hi @tshaiman,
Thanks for the report. I understand your first comment about the times being in different timezones (UTC versus local). I'm not sure I follow points (2) and (3), when you say:
```
 2

the NewTasks table is always empty

3
please check if the COUNT(DISTINCT E.[InstanceID]), needs to be distinct.
```

are (2) and (3) related to the timestamp issue, are they alternative explanations of the problem, or simply other observations? Just trying to gather up context. Thanks!

cc/ @bachuv, since we had a MSSQL-backend scaling issue recently.

**Comment by tshaiman** [comment]
disregard item2/3. this is irrelevant 
i'm sorry for the confusion

**Comment by tshaiman** [comment]
@bhugot  @cgillum 
any insights on this ?

**Comment by tshaiman** [comment]
we had wrong assumption/ understanding on how the internal durable tables works. we have verified the correctness of them and the correctness of the store procedure.
