### ISSUE TITLE
SqlUtils doesn't support suspending

### ISSUE THREAD

**Issue by Kobudzik** [microsoft/durabletask-mssql#181]
Hello there,

I'm working on managing orchestration instances for my organization. Termination operation works fine, but suspending is not supported in SqlUtils.cs (and never was) - hence `System.InvalidOperationException: Don't know how to interpret 'ExecutionSuspended'` is thrown during history event handling. Is there any reason why it's not there, or was it just missed?

**Comment by cgillum** [comment]
Thanks for reporting this! We'll look into adding support for suspended orchestrations.

**Comment by mattj-MS** [comment]
Just wanted to comment this is killing us as well.

**Comment by cgillum** [comment]
Sorry that this fell off the radar. I've submitted a PR with a fix: https://github.com/microsoft/durabletask-mssql/pull/195.

**Comment by cgillum** [comment]
The fix for this has been released: https://github.com/microsoft/durabletask-mssql/releases/tag/v1.2.1
