### ISSUE TITLE
Support to host the taskhub as part of a vanila asp.net core webapp

### ISSUE THREAD

**Issue by gauravvgat** [microsoft/durabletask-mssql#189]
Hi,
I see that the durabletask framework is touted to run on serverless. Is it possible for me to host the worker/taskhub inside an asp.net core web application? The worker will be part of an application which is hosted on a VM and due to other technical requirements, serverless is not an option to host the app.

Can anyone point me to good examples where the taskhub is hosted in normal app as a background worker? I couldn't find any examples/documentation of this will look like.

**Comment by cgillum** [comment]
You can run the Durable Task Framework in any .NET app.  There's no requirement for serverless. You can find some examples (though they are quite old) [here](https://github.com/Azure/durabletask/tree/main/samples).

@jviau I believe you also have some extensions that make integration with ASP.NET more natural, right? Would you be able to share a link to those?

**Comment by gauravvgat** [comment]
Thanks @cgillum. Also I couldn't find any API to set custom status like in azure runtime. Am I missing some using statement or it's not available yet. 
If not available, what would you recommend to store custom status for an instance or activity.

**Comment by gauravvgat** [comment]
Thanks @jviau and @cgillum. Closing this as my queries are answered.
