### ISSUE TITLE
Under what circumstance does DTF SQL provider throws Duplicate execution error

### ISSUE THREAD

**Issue by jundayin** [microsoft/durabletask-mssql#214]
Would like to here input from DTFx expert
 
We notice the DTF throws error like `Duplicate execution of 'orchestration' was detected! This means two workers or threads tried to process the same work item simultaneously. The result of this execution will be discarded` on our customer machine which has SQL Server 2019 installed and the orchestration just stuck. Occasionally, there is also database connection timeout issue. However, we never encounter this problem on Azure SQL even with the lowest hardware setup.

This doesn't happen often, but it gave us headache on investigating the root cause. We were able to resolve the problem once when customer changed their disk to a more performant one. However, another customer with SSD disk also encountered this error which doesn't make sense to us.

It would be great if you as the owner of the framework could give us some insights regarding the duplicated execution
 
Current DT version: 1.0.0-rc

**Comment by cgillum** [comment]
Can you clarify what `1.0.0-rc` refers to? We don't have a Durable Task version of that number. Perhaps you're referring to a nuget package version, such as `Microsoft.DurableTask.SqlServer`?

Assuming so, that version is quite old and there may be bugs. It is recommended to upgrade to the latest version, such as `1.2.3`, which also includes important security fixes.

**Comment by jundayin** [comment]
Thanks @cgillum . Yes, I was referring the version of SQL Provider nuget package.

I understand it is rather old and we are planning to upgrade to latest version this year, but still we would like to understand the problem better to solve our customer issue.

Do you believe setting the max concurrent activity and orchestration to 1 can resolve the issue?

**Comment by jundayin** [comment]
@cgillum Any thought? It would be appreciated if you can provide us some insights of the issue here as we need to unblock out customer installation.

Something we are confused currently:
1. Under what circumstance there will be duplicated execution?
2. Do you believe set the max concurrent activity and orchestration can resolve the issue?
3. If not, how do we ensure the problem does not happen on the latest Microsoft.DurableTask.SqlServer
