### ISSUE TITLE
Always encrypted support for python

### ISSUE THREAD

**Issue by lorenzo-caruso** [microsoft/durabletask-mssql#215]
Hi,

I'm opening this issue to understand if is possible to use Always Encrypted / Column Encryption on the Payloads.Text column of the TaskHub database?

I found this [issue](https://github.com/microsoft/durabletask-mssql/issues/165), but I would like to know if is possible to do the same in python. 

If is not possible to do this, which are the other ways to encrypt the Payloads.Text column in which we will store sensitive data?

Thanks,
Lorenzo

**Comment by cgillum** [comment]
Hi @lorenzo-caruso. If the linked issue gets resolved, then it will work for any language, including Python on Azure Durable Functions. The implementation would be language-agnostic.
