### ISSUE TITLE
Could not use Durable Entities with Azure functions .NET isolated worker and SQL Storage Provider

### ISSUE THREAD

**Issue by vpalaparthy** [microsoft/durabletask-mssql#279]
We are trying to use Azure Durable Entities with .Net Isolated + SQL storage provider. We are getting exceptions while using Entities indicating that Durable Entities are not supported with SQL backend configuration.

configurations: 

host.json:
![Image](https://github.com/user-attachments/assets/baeae62d-8af7-44dd-b984-cb783fea2431)

local.settings.json: 
![Image](https://github.com/user-attachments/assets/f0acf2af-ded0-44a5-8c65-65b469166151)

Exception:
![Image](https://github.com/user-attachments/assets/ad4d62ce-a71b-4ad4-ad10-12b895e4bfb5)
 
code snippet: 
![Image](https://github.com/user-attachments/assets/adca4eef-9c18-4858-be61-20fc1eca2c23)

Referenced this article [Durable entities - Azure Functions | Microsoft Learn](https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-entities?tabs=function-based%2Cisolated-process%2Cpython-v2&pivots=csharp) and came to an understanding that Durable Entities are supported in .Net isolated mode.

Also tried another below code snipped resulting in similar exception. 
![Image](https://github.com/user-attachments/assets/93cbe13c-bde8-4080-bdb5-b036bd2bfdb6)

Exception: 
![Image](https://github.com/user-attachments/assets/c40e1941-cba6-4fdc-88cc-ed3ab061ec5e)

**Comment by cgillum** [comment]
Also, we've made an update to the documentation to help clarify that Durable Entities are not yet supported with the MSSQL backend when using .NET Isolated. Apologies for the confusion.

https://learn.microsoft.com/azure/azure-functions/durable/durable-functions-storage-providers#comparing-storage-providers

![Image](https://github.com/user-attachments/assets/f6be0a9a-353d-4d08-b0f2-812215c302ab)
