### ISSUE TITLE
Update Microsoft.Data.SqlClient dependency to v3.0.0

### ISSUE THREAD

**Issue by cgillum** [microsoft/durabletask-mssql#32]
Release notes: https://github.com/dotnet/SqlClient/blob/main/release-notes/3.0/3.0.0.md

Notable changes:
* This version has built-in support for Azure managed identities and could potentially allow us to simplify our own support for this.
* This version has built-in automatic retry support for transient errors (in preview). This could potentially replace our customer implementation.

**Comment by usemam** [comment]
@cgillum 
Please take a look at PR #33 - it essentially reverts changes that introduced Azure Managed Identity support and adds reference to Microsoft.Data.SqlClient package v3.0.0

**Comment by cgillum** [comment]
PR merged! This will go out with the v0.10.0 release.
