### ISSUE TITLE
Activity start time appears to be earlier than its orchestration start time

### ISSUE THREAD

**Issue by scale-tone** [microsoft/durabletask-mssql#37]
I'm observing this:
![image](https://user-images.githubusercontent.com/5447190/123527014-295c5c00-d6dc-11eb-9100-5c75f36a5b8e.png)

Everything was run on my devbox, aka on the same computing instance, so this cannot be explained as clock difference.
Is that normal?

**Comment by cgillum** [comment]
Just so I'm not making assumptions, where are you getting these values from?

**Comment by scale-tone** [comment]
That's what `DurableOrchestrationStatus.History` contains, returned by `DurableClient.GetStatusAsync(instanceId, true, true, true)`.
