### ISSUE TITLE
Azure Sql serverless sku

### ISSUE THREAD

**Issue by mdddev** [microsoft/durabletask-mssql#43]
Hello,

when using the serverless sku of an Azure Sql there can be times in which the db is _sleeping/paused_. It may take a minute or so to get spun-up again. Does this have any impact on durable orchestrations? Other than having to wait for the db to be ready of course.

Cheers

**Comment by cgillum** [comment]
Hi @mdddev, this behavior isn't expected to impact durable orchestrations. When your app is running, it's regularly polling the database, which should prevent it from going to sleep. But even if you stop the app and allow the database to go to sleep, the cold-start delay will only impact the time it takes for the app to finish starting up and processing orchestrations again.

If the first request is something like a status query operation via `TaskHubClient`, then that request may experience a timeout, depending on how long it takes for the database to "wake up". That might impact your client application, but it won't have any impact on durable orchestration processing.

I hope this answers your question. Let me know if you have others.
