### ISSUE TITLE
Plans to support .NET Framework?

### ISSUE THREAD

**Issue by usemam** [microsoft/durabletask-mssql#5]
@cgillum 
Any plans on bumping TargetFramework for DurableTask.SqlServer package down to netstandard2.0?
This will enable support for older .NET versions, such as .NET Framework 4.8
Thanks!

**Comment by cgillum** [comment]
@usemam yes, I received a few other requests for .NET Framework support and plan and adding it soon. One thing I need to decide is whether to multi-target both .NET Standard 2.1 and .NET Framework 4.6.2 (the version of of our internal partners require) or to just target .NET Standard 2.0. Let me know if you have thoughts on this.

**Comment by usemam** [comment]
@cgillum
IMO, biggest pain-point of targeting just .NET Standard 2.0 is unfortunately getting rid of IAsyncDisposable usages in DurableTask.SqlServer\SqlDbManager.

**Comment by cgillum** [comment]
I ended up targeting both .NET Standard 2.1 and .NET Standard 2.0. It turns out there are some tricks you can do to support `IAsyncDisposable`, even in .NET Standard 2.0, so the changes weren't too bad.
