### ISSUE TITLE
Distributed Tracing

### ISSUE THREAD

**Issue by cgillum** [microsoft/durabletask-mssql#57]
The MSSQL provider doesn't currently support the [Durable Task Distributed Tracing](https://github.com/Azure/durabletask/tree/main/samples/Correlation.Samples#distributed-tracing-for-durable-task), which is necessary for end-to-end correlation in distributed apps. This item tracks adding support.

**Comment by BraedonWooding** [comment]
@cgillum I'm interested in supporting this (going to build it anyways for our needs, so I want to push it back for others if possible).

Given that I've got a strong reference in the azure storage implementation and a strong confidence in how to implement something like this.

From reading all the various documentation looks like the first blocker is just WorkItems needing a TraceContext, I'll start then.

TraceContext is already a column in the DurableTasks.Instances so likely the work required to set it then fetch it will be pretty minor.

**Comment by cgillum** [comment]
Ah, so I actually just finished implementing this and forgot to link the PR to this GitHub issue: https://github.com/microsoft/durabletask-mssql/pull/190.

I don’t yet have instructions or a sample, but take a look at the test case in the PR to see if the current implementation might work for you.
