### ISSUE TITLE
Documentation: Updated Performance Comparisons

### ISSUE THREAD

**Issue by cgillum** [microsoft/durabletask-mssql#60]
Documentation exists that covers the [performance numbers for the MSSQL backend](https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale#scale), but it hasn't been updated for quite a while. Since then, several new features have been added and performance improving fixes have been made. As part of the v1.0.0 release, we need to update this documentation with up-to-date numbers. Ideally, we'll also include a couple more scenarios in addition to "Hello Cities".

**Comment by cgillum** [comment]
Updated numbers have been added. I decided to keep the "Hello Cities" scenario as-is since it turns out to be pretty representative of real-world usage.

**Comment by IGx89** [comment]
Hi! Would you mind sharing a link to this document with performance numbers? The linked document above doesn't mention MSSQL.

**Comment by cgillum** [comment]
https://microsoft.github.io/durabletask-mssql/#/scaling?id=orchestration-throughput-benchmarks
